package uk.co.automatictester.bas.specs;

import com.atlassian.bamboo.specs.api.builders.BambooKey;
import com.atlassian.bamboo.specs.api.builders.deployment.Deployment;
import com.atlassian.bamboo.specs.api.builders.permission.*;
import com.atlassian.bamboo.specs.api.builders.plan.Plan;

public abstract class PlanConfig {

    protected static final String DEFAULT_DESCRIPTION = "Config generated automatically from Bamboo Spec. Any manual changes will be lost when it gets autogenerated again";
    protected static final String PROJECT_NAME = "Swarm";

    public abstract BambooKey getPlanKey();

    public abstract Plan getPlan();

    protected BambooKey getProjectKey() {
        return new BambooKey("SWAR");
    }

    public boolean hasDeploymentPlan() {
        return false;
    }

    public Deployment getDeploymentPlan() {
        throw new RuntimeException("This build plan has no deployment plans");
    }

    public DeploymentPermissions getDeploymentPermission() {
        throw new RuntimeException("This build plan has no deployment permission");
    }

    public EnvironmentPermissions getEnvironmentPermission() {
        throw new RuntimeException("This build plan has no environment permission");
    }

    public PlanPermissions getPermissions() {
        return new PlanPermissions(getProjectKey(), getPlanKey()).permissions(
                new Permissions().userPermissions(
                        ServerConfig.getAdminUser(), PermissionType.EDIT, PermissionType.VIEW, PermissionType.ADMIN, PermissionType.CLONE, PermissionType.BUILD));
    }
}
