---
- name: Get docker image
  hosts: swarm_cluster
  tasks:
    - name: ECR login
      shell: $(aws ecr get-login --no-include-email --region {{ aws.region }})
    - name: Get aws account
      aws_caller_facts:
      register: aws_details
    - name: Set fact image_name
      set_fact:
        image_name: "{{ aws_details.account }}.dkr.ecr.{{ aws.region }}.amazonaws.com/{{ app.name }}:{{ simple_app_version }}"
    - name: Debug fact image_name
      debug: var=image_name
    - name: Pull docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

- name: Create service
  hosts: swarm_managers
  run_once: true
  tasks:
    - name: Create service
      docker_swarm_service:
        name: "{{ app.name }}"
        image: "{{ image_name }}"
        replicas: 3
        publish:
          - published_port: 8080
            target_port: 8080

- name: Cleanup
  hosts: swarm_cluster
  tasks:
    - name: Cleanup containers
      shell: docker container prune --force
    - name: Cleanup images
      shell: docker image prune --all --force